[package]
name = "api"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
argon2 = "0.5"
async-trait.workspace = true
axum = "0.8.9"
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
dotenvy = "0.15.7"
music = { path = "../music" }
percent-encoding = "2.3.2"
rpassword = "7"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2 = "0.10"
sqlx = { version = "0.8.6", default-features = false, features = ["any", "sqlite", "postgres", "runtime-tokio", "tls-rustls", "migrate", "macros"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tower-http = { version = "0.7.1", features = ["cors", "trace"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["json", "env-filter"] }
url = "2.5.8"
uuid = { version = "1.26.1", features = ["v7"] }

[dev-dependencies]
futures-util = "0.3"
midly = "0.5.3"
tempfile = "3.27.0"
wiremock = "0.6.5"
http-body-util = "0.1.5"
tokio = { workspace = true, features = ["test-util"] }
tower = "0.5.3"
